name: Playwright Pytest Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # or your preferred version

    # 3. Install dependencies
    - name: Install dependencies and Playwright
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        python -m playwright install

    # 4. Run Playwright + Pytest tests
    - name: Run tests
      run: |
        source venv/bin/activate
        pytest

